# FindMartialBundle/Resources/config/admin.yml
services:
    sonata.admin.tag:
        class: Acme\FindMartialBundle\Admin\MasterAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: masters, label: "Master" }
        arguments:
            - ~
            - Acme\FindMartialBundle\Entity\Master
            - 'AcmeFindMartialBundle:MasterAdmin'
        calls:
            - [ setTranslationDomain, [AcmeFindMartialBundle]]