acme_find_martial_homepage:
    pattern:  /
    defaults: { _controller: AcmeFindMartialBundle:Default:index }
client_create:
    pattern:  /client_create
    defaults: { _controller: AcmeFindMartialBundle:Client:create }
client_success:
    pattern:  /client_success
    defaults: { _controller: AcmeFindMartialBundle:Client:success }
