parameters:
#    acme_find_martial.example.class: Acme\FindMartialBundle\Example

services:
#    acme_find_martial.example:
#        class: %acme_find_martial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_find_martial.registration.form.type:
        class: Acme\FindMartialBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acme_find_martial_registration }
