jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Acme\FindMartialBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_CLIENT:      ROLE_USER
        ROLE_MASTER:      ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_CLIENT, ROLE_MASTER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #login:
        #    pattern:  ^/login$
        #    security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/master$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #- { path: ^/profile, 					role: [ROLE_USER, ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master/new, 				role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master/delete, 			role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master/edit, 				role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_client/assign,		role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_client/resign,		role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_client/approve, 	role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_client/disapprove,  role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_club/assign,		role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_club/resign,		role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_club/approve, 		role: [ROLE_CLIENT, ROLE_MASTER] }
        #- { path: ^/master_club/disapprove, 	role: [ROLE_CLIENT, ROLE_MASTER] }
                        
        #- { path: ^/clubs/edit, role: [ROLE_CLIENT, ROLE_MASTER] }
        
        - { path: ^/admin/, role: ROLE_ADMIN }
