// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App.AjaxForm.Customized = (function(_super) {

    __extends(Customized, _super);

    function Customized() {
      return Customized.__super__.constructor.apply(this, arguments);
    }

    Customized.prototype.enableArtsForm = function(content) {
      var master;
      master = JSON.parse(content);
      $('#acme_findmartialbundle_masterarttype_master').val(master.master);
      return showBlockForm("block2");
    };

    Customized.prototype.callbackMasterArtSave = function(content) {
      var list, masterArt, masterArts, _i, _len;
      masterArts = JSON.parse(content);
      list = $('<ul />', {
        "class": 'masterArtListHtml'
      });
      for (_i = 0, _len = masterArts.length; _i < _len; _i++) {
        masterArt = masterArts[_i];
        this.artAppend(list, masterArt);
      }
      return $('.masterArtListBlock .masterArtListHtml').replaceWith(list);
    };

    Customized.prototype.artAppend = function(list, art) {
      var buttonClose, buttonDelete, buttonEdit, buttonSave, iconAdd, iconCancel, iconCheck, iconDel, iconEdit, iconExp, iconTrExp, liBlock, liForm, liItem, spanFormTools, spanTools;
      this.list = list;
      liBlock = $('<li />', {
        "class": 'masterArtListBlock'
      });
      liItem = $('<div />', {
        "class": 'masterArtListItem'
      });
      liForm = $('<div />', {
        "class": 'masterArtListForm',
        style: 'display:none;'
      });
      iconAdd = $('<i />', {
        "class": 'fa fa-plus fa-fw'
      });
      iconEdit = $('<i />', {
        "class": 'fa fa-edit fa-fw'
      });
      iconDel = $('<i />', {
        "class": 'fa fa-trash-o fa-fw'
      });
      iconExp = $('<i />', {
        "class": 'fa fa-user fa-fw'
      });
      iconTrExp = $('<i />', {
        "class": 'fa fa-users fa-fw'
      });
      iconCheck = $('<i />', {
        "class": 'fa fa-check fa-fw'
      });
      iconCancel = $('<i />', {
        "class": 'fa fa-times fa-fw'
      });
      buttonEdit = $('<a />', {
        "class": 'buttonEdit',
        href: '#'
      }).append(iconEdit.clone(false));
      buttonDelete = $('<a />', {
        "class": 'buttonDelete',
        href: '#'
      }).append(iconDel.clone(false));
      spanTools = $('<span />', {
        "class": 'artListItemAcc'
      });
      spanTools.append(buttonEdit);
      spanTools.append('&nbsp;');
      spanTools.append(buttonDelete);
      buttonSave = $('<a />', {
        "class": 'buttonSave',
        href: '#'
      }).append(iconCheck.clone(false));
      buttonClose = $('<a />', {
        "class": 'buttonClose',
        href: '#'
      }).append(iconCancel.clone(false));
      spanFormTools = $('<span />', {
        "class": 'artListItemAcc'
      });
      spanFormTools.append(buttonSave);
      spanFormTools.append('&nbsp;');
      spanFormTools.append(buttonClose);
      liBlock.append($('<div />', {
        "class": 'artCol'
      }).append($('<span />', {
        "class": 'artListItemAcc',
        html: art.art
      })));
      liItem.append($('<div />', {
        "class": 'expirienceCol'
      }).append($('<span />', {
        "class": 'artListItemAcc',
        html: art.expirience
      })));
      liItem.append($('<div />', {
        "class": 'trainingExpCol'
      }).append($('<span />', {
        "class": 'artListItemAcc',
        html: art.training_exp
      })));
      liItem.append($('<div />', {
        "class": 'descriptionCol'
      }).append($('<span />', {
        "class": 'artListItemAcc',
        html: art.description
      })));
      liItem.append($('<div />', {
        "class": 'toolsCol'
      }).append(spanTools));
      liForm.append($('<div />', {
        "class": 'expirienceCol'
      }).append($('<span />', {
        "class": 'artListItemAcc'
      }).append($('<input />', {
        type: 'number'
      }))));
      liForm.append($('<div />', {
        "class": 'trainingExpCol'
      }).append($('<span />', {
        "class": 'artListItemAcc'
      }).append($('<input />', {
        type: 'number'
      }))));
      liForm.append($('<div />', {
        "class": 'descriptionCol'
      }).append($('<span />', {
        "class": 'artListItemAcc'
      }).append($('<input />', {
        type: 'text'
      }))));
      liForm.append($('<div />', {
        "class": 'toolsCol'
      }).append(spanFormTools));
      liBlock.append(liItem);
      liBlock.append(liForm);
      return list.append(liBlock);
    };

    return Customized;

  })(App.AjaxForm.Default);

  new App.AjaxForm.Customized('.ajax-form');

}).call(this);
